### ISSUE TITLE
Tests fail on import KDBX archives

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/buttercup-core#20]
Errors like the following occur randomly:

	importKDBXTests
	✔ containsInHistory - testContainsNotes
	✔ containsInHistory - testContainsPassword
	✔ containsItems - testContainsRootGroup
	✖ containsItems - testContainsSubGroup

	Assertion Message: Imported archive should contain sub group
	AssertionError: Imported archive should contain sub group
	    at Object.ok (/Users/pez/Git/buttercup-core/node_modules/nodeunit/lib/types.js:83:39)
	    at Object.module.exports.containsItems.testContainsSubGroup (/Users/pez/Git/buttercup-core/tests/integration/importKDBXTests.js:54:9)
	    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/lib/core.js:232:20
	    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:168:13
	    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:131:25
	    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:165:17
	    at /Users/pez/Git/buttercup-core/node_modules/nodeunit/deps/async.js:463:34
	    at /Users/pez/Git/buttercup-core/tests/integration/importKDBXTests.js:17:9

**Comment by perry-mitchell** [comment]
Fixed - parseInt issue
